{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "mew.fullname" . }}-gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mew.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.hostname }}
      tls:
        mode: Terminate
        options:
          networking.gke.io/pre-shared-certs: {{ .Values.gateway.tls.certificateName }}
      allowedRoutes:
        namespaces:
          from: Same
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.gateway.hostname }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
