{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mew.fullname" . }}-https
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mew.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "mew.fullname" . }}-gateway
      sectionName: https
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "mew.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
