{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mew.fullname" . }}-http-redirect
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mew.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "mew.fullname" . }}-gateway
      sectionName: http
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}
